blank_issues_enabled: false
contact_links:
  - name: ❓ Duda general
    url: https://github.com/Mendana/teamwork-ac-2025/discussions
    about: Usa discusiones para preguntas que no sean tareas específicas
